version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: always
  micrometer-prometheus-api:
    image: micrometer-prometheus-api
    container_name: micrometer-prometheus-api
    ports:
      - 18080:8080
