global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'micrometer-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - micrometer-prometheus-api:8080
